version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: ativ4DB
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ativ4DB
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
